name: cube-grasping
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - blas
  - bzip2
  - ca-certificates
  - certifi
  - cudatoolkit
  - ffmpeg
  - freetype
  - gmp
  - gnutls
  - imageio
  - jpeg
  - lame
  - ncurses
  - nettle
  - ninja
  - numpy
  - numpy-base
  - olefile
  - openh264
  - openssl
  - pillow
  - pip
  - python=3.8
  - pytorch
  - readline
  - setuptools
  - six
  - sqlite
  - tk
  - torchaudio
  - torchinfo
  - torchvision
  - typing_extensions
  - wheel
  - pip:
    - absl-py
    - alembic
    - attrs
    - awscli
    - backcall
    - botocore
    - cachetools
    - chardet
    - cliff
    - cloudpickle
    - cmaes
    - cmd2
    - colorama
    - colorlog
    - cycler
    - decorator
    - docopt
    - docutils
    - flatbuffers
    - gitdb
    - gitpython
    - google-auth
    - google-auth-oauthlib
    - greenlet
    - grpcio
    - gym
    - hydra-core==0.11
    - idna
    - imageio-ffmpeg
    - importlib-metadata
    - ipdb
    - ipython
    - ipython-genutils
    - jax
    - jaxlib
    - jedi
    - jmespath
    - joblib
    - jsonpickle
    - kiwisolver
    - kornia
    - mako
    - markdown
    - markupsafe
    - matplotlib
    - matplotlib-inline
    - mkl
    - mkl-service
    - mkl_fft
    - mkl_random
    - munch
    - oauthlib
    - opencv-python
    - opt-einsum
    - optuna
    - packaging
    - pandas
    - parso
    - pbr
    - pexpect
    - pickleshare
    - prettytable
    - prompt-toolkit
    - protobuf
    - psutil
    - ptyprocess
    - py-cpuinfo
    - pyasn1
    - pyasn1-modules
    - pybullet
    - pyglet
    - pygments
    - pyparsing
    - pyperclip
    - python-dateutil
    - python-editor
    - pytz
    - pyyaml
    - requests
    - requests-oauthlib
    - rsa
    - s3transfer
    - sacred
    - sb3-contrib
    - scikit-learn
    - scipy
    - seaborn
    - sklearn
    - smmap
    - sqlalchemy
    - stevedore
    - tb-nightly
    - tensorboard
    - tensorboard-data-server
    - tensorboard-plugin-wit
    - termcolor
    - threadpoolctl
    - toml
    - torch
    - tqdm
    - traitlets
    - urllib3
    - wcwidth
    - werkzeug
    - wrapt
    - yapf
    - zipp
